### ISSUE TITLE
some question about dataset

### ISSUE THREAD

**Issue by SSOTTY** [PreferredAI/beacon#2]
Hello Duc-Trong Le,
    When I work with datasets, I have some question:
1. Foursqaure contains 378 days in total, but the paper says that only 11 months have been taken. How exactly is it taken?

2. I used the method in your paper to process the data set, but the result has been very poor. For example,for _f1@10_,2.16 in delicious and 2.15 in foursquare.Could you open the processed data set?

Thank you for watching.

**Comment by HerrZYZ** [comment]
Do you know what's the add_tuple in the utils.py(line 99)? Is that a function?

**Comment by trongld** [comment]
@SSOTTY : 
1. Foursquare contains 378 days in total, but the paper says that only 11 months have been taken. How exactly is it taken?

=> We said "from Aug 2010 to Jul 2011", not 11 months. We use entire dataset. 

2. I used the method in your paper to process the data set, but the result has been very poor. For example,for f1@10,2.16 in delicious and 2.15 in foursquare.Could you open the processed data set?

=>  I will share one of our processed dataset today.

**Comment by trongld** [comment]
Hi @SSOTTY: Please download a sample here: https://drive.google.com/open?id=1EFv-heS2ObpOmWZMTrck87UbLpMwixFG
